package com.onemoney.recgardecardservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RechargeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRechargeAllPropertiesEquals(Recharge expected, Recharge actual) {
        assertRechargeAutoGeneratedPropertiesEquals(expected, actual);
        assertRechargeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRechargeAllUpdatablePropertiesEquals(Recharge expected, Recharge actual) {
        assertRechargeUpdatableFieldsEquals(expected, actual);
        assertRechargeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRechargeAutoGeneratedPropertiesEquals(Recharge expected, Recharge actual) {
        assertThat(actual)
            .as("Verify Recharge auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRechargeUpdatableFieldsEquals(Recharge expected, Recharge actual) {
        assertThat(actual)
            .as("Verify Recharge relevant properties")
            .satisfies(a -> assertThat(a.getAccoundId()).as("check accoundId").isEqualTo(expected.getAccoundId()))
            .satisfies(a -> assertThat(a.getAmount()).as("check amount").isEqualTo(expected.getAmount()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRechargeUpdatableRelationshipsEquals(Recharge expected, Recharge actual) {
        assertThat(actual)
            .as("Verify Recharge relationships")
            .satisfies(a -> assertThat(a.getCard()).as("check card").isEqualTo(expected.getCard()));
    }
}
